# -*- coding: utf-8 -*-
"""entrenamiento_billetes.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/12tYkauA6lAU5kl5OtQ9QjFhLy1v-A2dT

# Clasificación de billetes mexicanos con Transfer Learning

Notebook completo para entrenar un modelo de clasificación de billetes mexicanos usando MobileNetV3-Small con transfer learning, listo para exportar a TensorFlow Lite para una app móvil.

**Pipeline:**
1. Conectar Google Drive
2. Cargar y explorar el dataset
3. Preparar datasets con augmentations
4. Construir modelo MobileNetV3-Small con transfer learning
5. Fase 1: entrenar cabeza con backbone congelado
6. Fase 2: fine-tuning con backbone descongelado
7. Evaluar con matriz de confusión
8. Exportar a TensorFlow Lite (FP32 e INT8 cuantizado)

**Requisitos previos:**
- Estás corriendo esto en Google Colab con GPU activada (Entorno de ejecución → Cambiar tipo de entorno de ejecución → T4 GPU)
- Tu dataset está en Drive con estructura `dataset_final/train/<clase>/`, `dataset_final/valid/<clase>/`, `dataset_final/test/<clase>/`

## 1. Conectar Google Drive y configurar rutas
"""

from google.colab import drive
drive.mount('/content/drive')

# AJUSTA ESTA RUTA a donde tengas tu dataset en Drive
DATASET_PATH = '/content/drive/MyDrive/Billetes_mx/dataset_final'

# Donde guardar modelos y resultados
OUTPUT_PATH = '/content/drive/MyDrive/Billetes_mx/modelos'

import os
os.makedirs(OUTPUT_PATH, exist_ok=True)

# Verifica que las carpetas existen
for split in ['train', 'valid', 'test']:
    path = os.path.join(DATASET_PATH, split)
    if os.path.exists(path):
        clases = sorted(os.listdir(path))
        print(f'✓ {split}: {len(clases)} clases → {clases}')
    else:
        print(f'✗ FALTA: {path}')

"""## 2. Verificar versión de TF e imports"""

import tensorflow as tf
import numpy as np
import matplotlib.pyplot as plt
from pathlib import Path

print(f'TensorFlow version: {tf.__version__}')
print(f'GPU disponible: {tf.config.list_physical_devices("GPU")}')

# Configurar semilla para reproducibilidad
SEED = 42
tf.random.set_seed(SEED)
np.random.seed(SEED)

"""## 3. Explorar el dataset (conteo por clase y por split)"""

def contar_imagenes(ruta_split):
    conteo = {}
    for clase in sorted(os.listdir(ruta_split)):
        clase_dir = os.path.join(ruta_split, clase)
        if os.path.isdir(clase_dir):
            imgs = [f for f in os.listdir(clase_dir)
                    if f.lower().endswith(('.jpg', '.jpeg', '.png'))]
            conteo[clase] = len(imgs)
    return conteo

splits = ['train', 'valid', 'test']
conteos = {s: contar_imagenes(os.path.join(DATASET_PATH, s)) for s in splits}

# Tabla resumen
clases = sorted(set().union(*[c.keys() for c in conteos.values()]))
print(f'{"Clase":<15} | {"Train":>8} | {"Valid":>8} | {"Test":>8} | {"Total":>8}')
print('-' * 60)
for c in clases:
    t = conteos['train'].get(c, 0)
    v = conteos['valid'].get(c, 0)
    te = conteos['test'].get(c, 0)
    print(f'{c:<15} | {t:>8} | {v:>8} | {te:>8} | {t+v+te:>8}')
print('-' * 60)
print(f'{"TOTAL":<15} | {sum(conteos["train"].values()):>8} | '
      f'{sum(conteos["valid"].values()):>8} | {sum(conteos["test"].values()):>8} | '
      f'{sum(sum(c.values()) for c in conteos.values()):>8}')

"""## 4. Cargar datasets con tf.data"""

# Hiperparámetros
IMG_SIZE = (224, 224)
BATCH_SIZE = 32

train_ds = tf.keras.utils.image_dataset_from_directory(
    os.path.join(DATASET_PATH, 'train'),
    image_size=IMG_SIZE,
    batch_size=BATCH_SIZE,
    label_mode='categorical',
    shuffle=True,
    seed=SEED,
)

val_ds = tf.keras.utils.image_dataset_from_directory(
    os.path.join(DATASET_PATH, 'valid'),
    image_size=IMG_SIZE,
    batch_size=BATCH_SIZE,
    label_mode='categorical',
    shuffle=False,
)

test_ds = tf.keras.utils.image_dataset_from_directory(
    os.path.join(DATASET_PATH, 'test'),
    image_size=IMG_SIZE,
    batch_size=BATCH_SIZE,
    label_mode='categorical',
    shuffle=False,
)

CLASS_NAMES = train_ds.class_names
NUM_CLASSES = len(CLASS_NAMES)
print(f'\nClases ({NUM_CLASSES}): {CLASS_NAMES}')

# Guardar el mapeo de clases (CRÍTICO para la app móvil)
with open(os.path.join(OUTPUT_PATH, 'class_names.txt'), 'w') as f:
    for i, name in enumerate(CLASS_NAMES):
        f.write(f'{i}\t{name}\n')
print(f'\n✓ Mapeo de clases guardado en {OUTPUT_PATH}/class_names.txt')

# Optimizar pipeline con cache y prefetch
AUTOTUNE = tf.data.AUTOTUNE
train_ds = train_ds.cache().prefetch(buffer_size=AUTOTUNE)
val_ds = val_ds.cache().prefetch(buffer_size=AUTOTUNE)
test_ds = test_ds.cache().prefetch(buffer_size=AUTOTUNE)

"""## 5. Visualizar algunas imágenes del dataset"""

plt.figure(figsize=(14, 8))
for images, labels in train_ds.take(1):
    for i in range(min(12, len(images))):
        plt.subplot(3, 4, i + 1)
        plt.imshow(images[i].numpy().astype('uint8'))
        clase_idx = tf.argmax(labels[i]).numpy()
        plt.title(CLASS_NAMES[clase_idx])
        plt.axis('off')
plt.tight_layout()
plt.show()

"""## 6. Definir augmentations

Estas se aplican SOLO durante el entrenamiento, dentro del modelo. Para inferencia se desactivan automáticamente.
"""

data_augmentation = tf.keras.Sequential([
    tf.keras.layers.RandomFlip('horizontal'),
    tf.keras.layers.RandomRotation(0.15),       # ±54° aprox
    tf.keras.layers.RandomZoom(0.15),
    tf.keras.layers.RandomContrast(0.2),
    tf.keras.layers.RandomBrightness(0.2),
    tf.keras.layers.RandomTranslation(0.1, 0.1),
], name='data_augmentation')

# Visualizar augmentations
plt.figure(figsize=(12, 8))
for images, labels in train_ds.take(1):
    imagen_original = images[0]
    for i in range(9):
        plt.subplot(3, 3, i + 1)
        if i == 0:
            plt.imshow(imagen_original.numpy().astype('uint8'))
            plt.title('Original')
        else:
            aug = data_augmentation(tf.expand_dims(imagen_original, 0), training=True)
            plt.imshow(tf.cast(aug[0], tf.uint8).numpy())
            plt.title(f'Aug {i}')
        plt.axis('off')
plt.tight_layout()
plt.show()

"""## 7. Construir el modelo (MobileNetV3-Small + transfer learning)"""

# Cargar MobileNetV3-Small preentrenado en ImageNet
# include_top=False quita la última capa de 1000 clases de ImageNet
base_model = tf.keras.applications.MobileNetV3Small(
    input_shape=IMG_SIZE + (3,),
    include_top=False,
    weights='imagenet',
    include_preprocessing=True,  # IMPORTANTE: incluye la normalización dentro del modelo
)

# Congelar el backbone para Fase 1
base_model.trainable = False

# Construir el modelo completo
inputs = tf.keras.Input(shape=IMG_SIZE + (3,))
x = data_augmentation(inputs)
x = base_model(x, training=False)
x = tf.keras.layers.GlobalAveragePooling2D()(x)
x = tf.keras.layers.Dropout(0.3)(x)
outputs = tf.keras.layers.Dense(NUM_CLASSES, activation='softmax')(x)

model = tf.keras.Model(inputs, outputs)

model.summary()

"""## 8. Calcular pesos por clase (para balancear si hay desbalance)"""

from sklearn.utils.class_weight import compute_class_weight

# Reconstruir lista de etiquetas del train set
train_dir = os.path.join(DATASET_PATH, 'train')
y_train = []
for idx, clase in enumerate(CLASS_NAMES):
    n = len([f for f in os.listdir(os.path.join(train_dir, clase))
             if f.lower().endswith(('.jpg', '.jpeg', '.png'))])
    y_train.extend([idx] * n)
y_train = np.array(y_train)

class_weights_array = compute_class_weight(
    class_weight='balanced',
    classes=np.arange(NUM_CLASSES),
    y=y_train
)
class_weights = {i: w for i, w in enumerate(class_weights_array)}

print('Pesos por clase (mayor = clase con menos datos):')
for i, w in class_weights.items():
    print(f'  {CLASS_NAMES[i]:<15} → {w:.3f}')

"""## 9. FASE 1: Entrenar la cabeza con backbone congelado"""

model.compile(
    optimizer=tf.keras.optimizers.Adam(learning_rate=1e-3),
    loss='categorical_crossentropy',
    metrics=['accuracy', tf.keras.metrics.TopKCategoricalAccuracy(k=2, name='top2_acc')]
)

callbacks_fase1 = [
    tf.keras.callbacks.EarlyStopping(
        monitor='val_accuracy', patience=5, restore_best_weights=True, verbose=1
    ),
    tf.keras.callbacks.ReduceLROnPlateau(
        monitor='val_loss', factor=0.5, patience=2, min_lr=1e-6, verbose=1
    ),
]

EPOCHS_FASE1 = 15

print('=== FASE 1: Entrenando solo la cabeza ===\n')
history1 = model.fit(
    train_ds,
    validation_data=val_ds,
    epochs=EPOCHS_FASE1,
    callbacks=callbacks_fase1,
    class_weight=class_weights,
)

"""## 10. FASE 2: Fine-tuning con backbone descongelado"""

# Descongelar el backbone
base_model.trainable = True

# Pero congelar las primeras capas (las que detectan features básicas: bordes, texturas)
# Solo entrenamos las últimas, que son las más específicas
fine_tune_at = len(base_model.layers) // 2  # descongela mitad superior
for layer in base_model.layers[:fine_tune_at]:
    layer.trainable = False

trainable_layers = sum(1 for l in base_model.layers if l.trainable)
print(f'Capas entrenables del backbone: {trainable_layers} de {len(base_model.layers)}')

# Recompilar con learning rate MUY bajo
model.compile(
    optimizer=tf.keras.optimizers.Adam(learning_rate=1e-5),
    loss='categorical_crossentropy',
    metrics=['accuracy', tf.keras.metrics.TopKCategoricalAccuracy(k=2, name='top2_acc')]
)

callbacks_fase2 = [
    tf.keras.callbacks.EarlyStopping(
        monitor='val_accuracy', patience=7, restore_best_weights=True, verbose=1
    ),
    tf.keras.callbacks.ReduceLROnPlateau(
        monitor='val_loss', factor=0.5, patience=3, min_lr=1e-7, verbose=1
    ),
    tf.keras.callbacks.ModelCheckpoint(
        os.path.join(OUTPUT_PATH, 'mejor_modelo.keras'),
        monitor='val_accuracy', save_best_only=True, verbose=1
    ),
]

EPOCHS_FASE2 = 25

print('\n=== FASE 2: Fine-tuning ===\n')
history2 = model.fit(
    train_ds,
    validation_data=val_ds,
    epochs=EPOCHS_FASE2,
    callbacks=callbacks_fase2,
    class_weight=class_weights,
)

"""## 11. Graficar curvas de entrenamiento"""

# Combinar histories de ambas fases
acc = history1.history['accuracy'] + history2.history['accuracy']
val_acc = history1.history['val_accuracy'] + history2.history['val_accuracy']
loss = history1.history['loss'] + history2.history['loss']
val_loss = history1.history['val_loss'] + history2.history['val_loss']

fig, (ax1, ax2) = plt.subplots(1, 2, figsize=(14, 5))

ax1.plot(acc, label='Train')
ax1.plot(val_acc, label='Valid')
ax1.axvline(len(history1.history['accuracy']) - 1, color='red', linestyle='--', label='Inicio Fase 2')
ax1.set_xlabel('Época')
ax1.set_ylabel('Accuracy')
ax1.set_title('Accuracy')
ax1.legend()
ax1.grid(alpha=0.3)

ax2.plot(loss, label='Train')
ax2.plot(val_loss, label='Valid')
ax2.axvline(len(history1.history['loss']) - 1, color='red', linestyle='--', label='Inicio Fase 2')
ax2.set_xlabel('Época')
ax2.set_ylabel('Loss')
ax2.set_title('Loss')
ax2.legend()
ax2.grid(alpha=0.3)

plt.tight_layout()
plt.savefig(os.path.join(OUTPUT_PATH, 'curvas_entrenamiento.png'), dpi=100)
plt.show()

"""## 12. Evaluar en el set de test"""

test_loss, test_acc, test_top2 = model.evaluate(test_ds, verbose=1)
print(f'\n✓ Test accuracy: {test_acc*100:.2f}%')
print(f'✓ Test top-2 accuracy: {test_top2*100:.2f}%')

"""## 13. Matriz de confusión y reporte detallado"""

from sklearn.metrics import confusion_matrix, classification_report
import seaborn as sns

# Predicciones sobre todo el test set
y_true = []
y_pred = []
for images, labels in test_ds:
    preds = model.predict(images, verbose=0)
    y_true.extend(tf.argmax(labels, axis=1).numpy())
    y_pred.extend(tf.argmax(preds, axis=1).numpy())

y_true = np.array(y_true)
y_pred = np.array(y_pred)

# Matriz de confusión
cm = confusion_matrix(y_true, y_pred)
plt.figure(figsize=(10, 8))
sns.heatmap(cm, annot=True, fmt='d', cmap='Blues',
            xticklabels=CLASS_NAMES, yticklabels=CLASS_NAMES)
plt.xlabel('Predicción')
plt.ylabel('Real')
plt.title('Matriz de Confusión')
plt.tight_layout()
plt.savefig(os.path.join(OUTPUT_PATH, 'matriz_confusion.png'), dpi=100)
plt.show()

# Reporte por clase
print('\nReporte detallado por clase:\n')
print(classification_report(y_true, y_pred, target_names=CLASS_NAMES, digits=3))

"""## 14. Guardar el modelo en formato Keras"""

modelo_keras_path = os.path.join(OUTPUT_PATH, 'modelo_billetes.keras')
model.save(modelo_keras_path)
print(f'✓ Modelo Keras guardado en: {modelo_keras_path}')
print(f'  Tamaño: {os.path.getsize(modelo_keras_path) / (1024*1024):.2f} MB')

"""## 15. Exportar a TensorFlow Lite (FP32 - sin cuantizar)"""

converter = tf.lite.TFLiteConverter.from_keras_model(model)
tflite_fp32 = converter.convert()

tflite_fp32_path = os.path.join(OUTPUT_PATH, 'modelo_billetes_fp32.tflite')
with open(tflite_fp32_path, 'wb') as f:
    f.write(tflite_fp32)

print(f'✓ Modelo TFLite FP32 guardado')
print(f'  Tamaño: {os.path.getsize(tflite_fp32_path) / (1024*1024):.2f} MB')

"""## 16. Exportar a TensorFlow Lite cuantizado (INT8) — para móvil

Este es el archivo que vas a usar en tu app. Pesa ~4x menos y corre 2-3x más rápido en móvil.
"""

def representative_dataset():
    """Necesario para cuantización INT8. Pasa unas 100 imágenes representativas."""
    for images, _ in train_ds.take(100):
        for i in range(min(images.shape[0], 1)):  # 1 imagen por batch
            yield [tf.cast(images[i:i+1], tf.float32)]

converter = tf.lite.TFLiteConverter.from_keras_model(model)
converter.optimizations = [tf.lite.Optimize.DEFAULT]
converter.representative_dataset = representative_dataset
# Para máxima compatibilidad móvil dejamos input/output como float32
# pero los pesos internos se cuantizan a int8
tflite_int8 = converter.convert()

tflite_int8_path = os.path.join(OUTPUT_PATH, 'modelo_billetes_int8.tflite')
with open(tflite_int8_path, 'wb') as f:
    f.write(tflite_int8)

print(f'✓ Modelo TFLite INT8 cuantizado guardado')
print(f'  Tamaño: {os.path.getsize(tflite_int8_path) / (1024*1024):.2f} MB')

"""## 17. Verificar que el modelo TFLite cuantizado funciona"""

interpreter = tf.lite.Interpreter(model_path=tflite_int8_path)
interpreter.allocate_tensors()

input_details = interpreter.get_input_details()
output_details = interpreter.get_output_details()

print('Detalles de entrada:', input_details[0])
print('Detalles de salida:', output_details[0])

# Evaluar TFLite en el test set
correctas = 0
total = 0
for images, labels in test_ds:
    for i in range(images.shape[0]):
        img = tf.expand_dims(images[i], 0).numpy().astype(np.float32)
        interpreter.set_tensor(input_details[0]['index'], img)
        interpreter.invoke()
        pred = interpreter.get_tensor(output_details[0]['index'])
        if np.argmax(pred) == np.argmax(labels[i].numpy()):
            correctas += 1
        total += 1

print(f'\n✓ TFLite INT8 accuracy en test: {correctas/total*100:.2f}% ({correctas}/{total})')
print(f'  (modelo Keras original: {test_acc*100:.2f}%)')

"""## 18. Resumen final y archivos generados"""

print('=' * 60)
print('ARCHIVOS GENERADOS EN DRIVE')
print('=' * 60)
print(f'\nUbicación: {OUTPUT_PATH}\n')
for archivo in sorted(os.listdir(OUTPUT_PATH)):
    ruta = os.path.join(OUTPUT_PATH, archivo)
    tam = os.path.getsize(ruta) / (1024*1024)
    print(f'  • {archivo:<35} ({tam:.2f} MB)')

print('\n' + '=' * 60)
print('PARA TU APP MÓVIL USA:')
print('=' * 60)
print(f'  1. modelo_billetes_int8.tflite  ← este es el modelo')
print(f'  2. class_names.txt              ← este es el mapeo de clases')